hicheeluud/Django-labs/comedyclubs/comedyApp/urls.py
from django.urls import path
from comedyApp import views

app_name = 'comedyApp'

urlpatterns = [
    path('', views.ClubListView.as_view(), name='list'),
    path('<pk>/', views.ClubDetailView.as_view(),name='detail'),

]

hicheeluud/Django-labs/comedyclubs/comedyclubs/urls.py
from django.contrib import admin
from django.urls import path,include
from comedyApp import views

urlpatterns = [
    path('', views.IndexView.as_view()),
    path('admin/', admin.site.urls), 
    path('club_app/',include('comedyApp.urls', namespace='club')),
]

hicheeluud/Django-labs/comedyclubs/comedyApp/models.py
from django.db import models

# Create your models here.
class Club(models.Model):
    cname = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.cname
class Comedian(models.Model):
    coname = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    image = models.ImageField(blank=True, null=True, upload_to='static/images')
    club = models.ForeignKey(Club, related_name='clubs', on_delete=models.CASCADE)
    def __str__(self):
        return self.coname

hicheeluud/Django-labs/comedyclubs/comedyApp/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView
from . import models
from django.http import HttpResponse
class IndexView(View):
    print = 'Hello Django'
    def get(self, request):
        return HttpResponse('<h1>' + self.print + ' World</h1>')
class IndexView(TemplateView):
    template_name = 'index.html'
class ClubListView(ListView):
    context_object_name='clubList'
    model = models.Club
    template_name = 'club/club_list.html'

class ClubDetailView(DetailView):
    context_object_name='clubDetails'
    model = models.Club
    template_name ='club/club_detail.html'

hicheeluud/Django-labs/comedyclubs/templates/index.html
{% extends "layout.html" %}
{% block body_block %}

<div class="jumbotron">

    <h1>Монголын комеди клубууд вэб апп.</h1>

</div>

{% endblock %}

hicheeluud/Django-labs/comedyclubs/templates/layout.html
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <title>{%block title%} ComedyClub {%endblock title%}</title>
</head>

<body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'comedyApp:list' %}">Комеди клубууд</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Админ</a>
            </li>
        </ul>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>

</html>